import React from "react";
import { Sparkles, AlertTriangle, CheckCircle2, TrendingUp, Lightbulb } from "lucide-react";
import clsx from "clsx";

export interface OperationalInsights {
  observations: string[];
  recommendations: string[];
  risks: string[];
  bottlenecks: string[];
  opportunities: string[];
}

interface InsightCardProps {
  insights: OperationalInsights;
  className?: string;
}

export const InsightCard: React.FC<InsightCardProps> = ({ insights, className }) => {
  return (
    <div className={clsx("bg-slate-800/90 border border-teal-500/30 rounded-2xl p-5 space-y-4 shadow-lg relative overflow-hidden", className)}>
      <div className="flex items-center justify-between border-b border-slate-700/60 pb-3">
        <div className="flex items-center gap-2">
          <div className="p-1.5 bg-teal-500/10 border border-teal-500/30 rounded-xl text-teal-400">
            <Sparkles className="w-4 h-4" />
          </div>
          <div>
            <h3 className="text-sm font-bold text-white flex items-center gap-2">
              Agent 6 Operational Intelligence & Recommendations
              <span className="text-[10px] font-mono font-normal bg-teal-500/10 text-teal-300 border border-teal-500/30 px-2 py-0.5 rounded-full">
                Generated by InsightEngine
              </span>
            </h3>
            <p className="text-[11px] text-slate-400 font-mono">Executive brief for clinic owner</p>
          </div>
        </div>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-4 text-xs">
        {/* Observations & Bottlenecks */}
        <div className="space-y-3">
          <div className="bg-slate-900/60 border border-slate-700/50 rounded-xl p-3.5 space-y-1.5">
            <span className="text-[10px] font-bold text-teal-400 uppercase tracking-wider flex items-center gap-1">
              <Lightbulb className="w-3.5 h-3.5" /> Top 5 Key Observations
            </span>
            <ul className="space-y-1 text-slate-300 list-disc list-inside">
              {insights.observations.map((obs, i) => (
                <li key={i}>{obs}</li>
              ))}
            </ul>
          </div>

          <div className="bg-slate-900/60 border border-amber-500/30 rounded-xl p-3.5 space-y-1.5">
            <span className="text-[10px] font-bold text-amber-400 uppercase tracking-wider flex items-center gap-1">
              <AlertTriangle className="w-3.5 h-3.5" /> Operational Bottlenecks
            </span>
            <ul className="space-y-1 text-slate-300 list-disc list-inside">
              {insights.bottlenecks.map((bot, i) => (
                <li key={i}>{bot}</li>
              ))}
            </ul>
          </div>
        </div>

        {/* Recommendations & Growth Opportunities */}
        <div className="space-y-3">
          <div className="bg-slate-900/60 border border-emerald-500/30 rounded-xl p-3.5 space-y-1.5">
            <span className="text-[10px] font-bold text-emerald-400 uppercase tracking-wider flex items-center gap-1">
              <CheckCircle2 className="w-3.5 h-3.5" /> Strategic Recommendations
            </span>
            <ul className="space-y-1 text-slate-300 list-disc list-inside">
              {insights.recommendations.map((rec, i) => (
                <li key={i}>{rec}</li>
              ))}
            </ul>
          </div>

          <div className="bg-slate-900/60 border border-purple-500/30 rounded-xl p-3.5 space-y-1.5">
            <span className="text-[10px] font-bold text-purple-300 uppercase tracking-wider flex items-center gap-1">
              <TrendingUp className="w-3.5 h-3.5" /> Growth Opportunities
            </span>
            <ul className="space-y-1 text-slate-300 list-disc list-inside">
              {insights.opportunities.map((opp, i) => (
                <li key={i}>{opp}</li>
              ))}
            </ul>
          </div>
        </div>
      </div>
    </div>
  );
};
