import React from "react";
import { Sparkles, Lightbulb, AlertTriangle, CheckCircle2, TrendingUp, Cpu } from "lucide-react";
import clsx from "clsx";

export interface OperationsInsightsData {
  generated_at: string;
  observations: string[];
  recommendations: string[];
  risks: string[];
  optimizations: string[];
  capacity_planning: string;
}

interface OperationsInsightCardProps {
  insights: OperationsInsightsData;
  className?: string;
}

export const OperationsInsightCard: React.FC<OperationsInsightCardProps> = ({ insights, className }) => {
  return (
    <div className={clsx("bg-slate-800/90 border border-teal-500/30 rounded-2xl p-5 space-y-4 shadow-lg relative overflow-hidden", className)}>
      <div className="flex items-center justify-between border-b border-slate-700/60 pb-3">
        <div className="flex items-center gap-2">
          <div className="p-1.5 bg-teal-500/10 border border-teal-500/30 rounded-xl text-teal-400">
            <Sparkles className="w-4 h-4" />
          </div>
          <div>
            <h3 className="text-sm font-bold text-white flex items-center gap-2">
              System Operations Briefing & Optimization
              <span className="text-[10px] font-mono font-normal bg-teal-500/10 text-teal-300 border border-teal-500/30 px-2 py-0.5 rounded-full">
                Generated by InsightEngine
              </span>
            </h3>
            <p className="text-[11px] text-slate-400 font-mono">Timestamp: {insights.generated_at}</p>
          </div>
        </div>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-4 text-xs">
        {/* Capacity & Platform Observations */}
        <div className="space-y-3">
          <div className="bg-slate-900/60 border border-slate-700/50 rounded-xl p-3.5 space-y-1">
            <span className="text-[10px] font-bold text-teal-400 uppercase tracking-wider block">GCP Capacity Planning</span>
            <p className="text-slate-200 leading-relaxed font-mono font-semibold">{insights.capacity_planning}</p>
          </div>

          <div className="bg-slate-900/60 border border-slate-700/50 rounded-xl p-3.5 space-y-1.5">
            <span className="text-[10px] font-bold text-blue-400 uppercase tracking-wider flex items-center gap-1">
              <Lightbulb className="w-3.5 h-3.5" /> Platform Observations
            </span>
            <ul className="space-y-1 text-slate-300 list-disc list-inside">
              {insights.observations.map((obs, i) => (
                <li key={i}>{obs}</li>
              ))}
            </ul>
          </div>
        </div>

        {/* Recommendations & Detected Risks */}
        <div className="space-y-3">
          <div className="bg-slate-900/60 border border-emerald-500/30 rounded-xl p-3.5 space-y-1.5">
            <span className="text-[10px] font-bold text-emerald-400 uppercase tracking-wider flex items-center gap-1">
              <CheckCircle2 className="w-3.5 h-3.5" /> System Optimization Suggestions
            </span>
            <ul className="space-y-1 text-slate-300 list-disc list-inside">
              {insights.optimizations.map((opt, i) => (
                <li key={i}>{opt}</li>
              ))}
            </ul>
          </div>

          <div className="bg-slate-900/60 border border-amber-500/30 rounded-xl p-3.5 space-y-1.5">
            <span className="text-[10px] font-bold text-amber-400 uppercase tracking-wider flex items-center gap-1">
              <AlertTriangle className="w-3.5 h-3.5" /> Detected Risks
            </span>
            <ul className="space-y-1 text-slate-300 list-disc list-inside">
              {insights.risks.map((r, i) => (
                <li key={i}>{r}</li>
              ))}
            </ul>
          </div>
        </div>
      </div>
    </div>
  );
};
