import React from "react";
import { Sparkles, ShieldAlert, CheckCircle2, AlertTriangle, Cpu, RefreshCw } from "lucide-react";
import clsx from "clsx";

export interface AISummaryContent {
  generated_at: string;
  patient_overview: string;
  clinical_history: string;
  risk_assessment: string;
  care_gaps: string[];
  missed_followups: string[];
  recommended_next_steps: string[];
  important_observations: string[];
}

interface AISummaryCardProps {
  summary: AISummaryContent;
  onRefresh?: () => void;
  className?: string;
}

export const AISummaryCard: React.FC<AISummaryCardProps> = ({ summary, onRefresh, className }) => {
  return (
    <div className={clsx("bg-slate-800/90 border border-teal-500/30 rounded-2xl p-5 space-y-4 shadow-lg relative overflow-hidden", className)}>
      {/* Accent Background Glow */}
      <div className="absolute -top-10 -right-10 w-40 h-40 bg-teal-500/5 rounded-full blur-2xl pointer-events-none" />

      {/* Header */}
      <div className="flex items-center justify-between flex-wrap gap-2 pb-3 border-b border-slate-700/60">
        <div className="flex items-center gap-2">
          <div className="p-1.5 bg-teal-500/10 border border-teal-500/30 rounded-xl text-teal-400">
            <Sparkles className="w-4 h-4" />
          </div>
          <div>
            <h3 className="text-sm font-bold text-white flex items-center gap-2">
              AI Longitudinal Clinical Summary
              <span className="text-[10px] font-mono font-normal bg-teal-500/10 text-teal-300 border border-teal-500/30 px-2 py-0.5 rounded-full">
                Generated by Agent 6 (InsightEngine)
              </span>
            </h3>
            <p className="text-[11px] text-slate-400 mt-0.5 font-mono">
              Timestamp: {summary.generated_at || "Just now"} • Powered by Gemini 1.5 Pro
            </p>
          </div>
        </div>

        {onRefresh && (
          <button
            onClick={onRefresh}
            className="text-xs text-teal-400 hover:text-teal-300 font-semibold flex items-center gap-1 bg-teal-500/10 px-2.5 py-1 rounded-lg border border-teal-500/30 transition-colors"
          >
            <RefreshCw className="w-3.5 h-3.5" /> Re-Analyze
          </button>
        )}
      </div>

      {/* Grid of Sections */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-4 text-xs">
        {/* Overview & History */}
        <div className="space-y-3">
          <div className="bg-slate-900/60 border border-slate-700/50 rounded-xl p-3.5 space-y-1">
            <span className="text-[10px] font-bold text-teal-400 uppercase tracking-wider block">Patient Overview</span>
            <p className="text-slate-200 leading-relaxed">{summary.patient_overview}</p>
          </div>

          <div className="bg-slate-900/60 border border-slate-700/50 rounded-xl p-3.5 space-y-1">
            <span className="text-[10px] font-bold text-blue-400 uppercase tracking-wider block">Clinical History</span>
            <p className="text-slate-300 leading-relaxed">{summary.clinical_history}</p>
          </div>
        </div>

        {/* Risk & Care Gaps */}
        <div className="space-y-3">
          <div className="bg-slate-900/60 border border-slate-700/50 rounded-xl p-3.5 space-y-1">
            <span className="text-[10px] font-bold text-rose-400 uppercase tracking-wider block">Risk Assessment</span>
            <p className="text-slate-200 leading-relaxed">{summary.risk_assessment}</p>
          </div>

          {summary.care_gaps.length > 0 && (
            <div className="bg-slate-900/60 border border-amber-500/30 rounded-xl p-3.5 space-y-1.5">
              <span className="text-[10px] font-bold text-amber-400 uppercase tracking-wider flex items-center gap-1">
                <AlertTriangle className="w-3 h-3" /> Care Gaps & Missed Follow-Ups ({summary.care_gaps.length})
              </span>
              <ul className="space-y-1 text-slate-300 list-disc list-inside">
                {summary.care_gaps.map((gap, i) => (
                  <li key={i}>{gap}</li>
                ))}
              </ul>
            </div>
          )}
        </div>
      </div>

      {/* Recommended Next Steps & Observations */}
      <div className="bg-teal-950/20 border border-teal-500/20 rounded-xl p-3.5 space-y-2 text-xs">
        <span className="text-[10px] font-bold text-teal-300 uppercase tracking-wider flex items-center gap-1">
          <CheckCircle2 className="w-3.5 h-3.5 text-teal-400" /> Recommended Action Plan & Next Steps
        </span>
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-2 text-slate-200">
          {summary.recommended_next_steps.map((step, idx) => (
            <div key={idx} className="flex items-start gap-1.5 bg-slate-900/50 p-2 rounded-lg border border-slate-800">
              <span className="text-teal-400 font-bold font-mono">{idx + 1}.</span>
              <span>{step}</span>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
};
