import React from "react";
import { Sparkles, AlertTriangle, TrendingUp, CheckCircle2, DollarSign } from "lucide-react";
import clsx from "clsx";

export interface BillingPulseInsights {
  generated_at: string;
  revenue_risks: string[];
  collection_opportunities: string[];
  delayed_payments: string[];
  revenue_forecast: string;
  recommendations: string[];
}

interface BillingInsightCardProps {
  insights: BillingPulseInsights;
  className?: string;
}

export const BillingInsightCard: React.FC<BillingInsightCardProps> = ({ insights, className }) => {
  return (
    <div className={clsx("bg-slate-800/90 border border-teal-500/30 rounded-2xl p-5 space-y-4 shadow-lg relative overflow-hidden", className)}>
      <div className="flex items-center justify-between border-b border-slate-700/60 pb-3">
        <div className="flex items-center gap-2">
          <div className="p-1.5 bg-teal-500/10 border border-teal-500/30 rounded-xl text-teal-400">
            <Sparkles className="w-4 h-4" />
          </div>
          <div>
            <h3 className="text-sm font-bold text-white flex items-center gap-2">
              BillingPulse Financial Intelligence & Forecast
              <span className="text-[10px] font-mono font-normal bg-teal-500/10 text-teal-300 border border-teal-500/30 px-2 py-0.5 rounded-full">
                Generated by BillingPulse
              </span>
            </h3>
            <p className="text-[11px] text-slate-400 font-mono">Timestamp: {insights.generated_at || "Just now"}</p>
          </div>
        </div>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-4 text-xs">
        {/* Forecast & Revenue Risks */}
        <div className="space-y-3">
          <div className="bg-slate-900/60 border border-slate-700/50 rounded-xl p-3.5 space-y-1">
            <span className="text-[10px] font-bold text-teal-400 uppercase tracking-wider block">7-Day Revenue Forecast</span>
            <p className="text-slate-200 leading-relaxed font-mono font-semibold">{insights.revenue_forecast}</p>
          </div>

          <div className="bg-slate-900/60 border border-rose-500/30 rounded-xl p-3.5 space-y-1.5">
            <span className="text-[10px] font-bold text-rose-400 uppercase tracking-wider flex items-center gap-1">
              <AlertTriangle className="w-3.5 h-3.5" /> Identified Revenue Risks
            </span>
            <ul className="space-y-1 text-slate-300 list-disc list-inside">
              {insights.revenue_risks.map((r, i) => (
                <li key={i}>{r}</li>
              ))}
            </ul>
          </div>
        </div>

        {/* Collection Opportunities & Recommendations */}
        <div className="space-y-3">
          <div className="bg-slate-900/60 border border-emerald-500/30 rounded-xl p-3.5 space-y-1.5">
            <span className="text-[10px] font-bold text-emerald-400 uppercase tracking-wider flex items-center gap-1">
              <TrendingUp className="w-3.5 h-3.5" /> Collection Opportunities
            </span>
            <ul className="space-y-1 text-slate-300 list-disc list-inside">
              {insights.collection_opportunities.map((o, i) => (
                <li key={i}>{o}</li>
              ))}
            </ul>
          </div>

          <div className="bg-slate-900/60 border border-purple-500/30 rounded-xl p-3.5 space-y-1.5">
            <span className="text-[10px] font-bold text-purple-300 uppercase tracking-wider flex items-center gap-1">
              <CheckCircle2 className="w-3.5 h-3.5" /> Financial Recommendations
            </span>
            <ul className="space-y-1 text-slate-300 list-disc list-inside">
              {insights.recommendations.map((rec, i) => (
                <li key={i}>{rec}</li>
              ))}
            </ul>
          </div>
        </div>
      </div>
    </div>
  );
};
